[tool.pytest.ini_options]
testpaths = [
    "src/tests",
]

[tool.briefcase]
project_name = "MovieFinder"
bundle = "com.example"
version = "0.1.0"
url = "https://github.com/chizuo/COMP587-MovieApplication"
license = "GNU General Public License v3 (GPLv3)"
author = 'John Chua and Chris Wheeler'
author_email = "christopher.wheeler.320@my.csun.edu"

[tool.briefcase.app.moviefinder]
formal_name = "MovieFinder"
description = "A movie recommender."
icon = "src/moviefinder/resources/moviefinder"
sources = ['src/moviefinder']
requires = [
    'arrow==1.2.3',
    'binaryornot==0.4.4',
    'briefcase==0.3.7',
    'certifi==2022.9.14',
    'chardet==5.0.0',
    'charset-normalizer==2.1.1',
    'commonmark==0.9.1',
    'cookiecutter==2.1.1',
    'gitdb==4.0.9',
    'GitPython==3.1.27',
    'idna==3.4',
    'iniconfig==1.1.1',
    'jinja2-time==0.2.0',
    'Jinja2==3.1.2',
    'MarkupSafe==2.1.1',
    'psutil==5.9.2',
    'Pygments==2.13.0',
    'PySide6-Addons==6.3.2',
    'PySide6-Essentials==6.3.2',
    'PySide6==6.3.2',
    'python-dateutil==2.8.2',
    'python-slugify==6.1.2',
    'PyYAML==6.0',
    'requests==2.28.1',
    'rich==12.5.1',
    'shiboken6==6.3.2',
    'six==1.16.0',
    'smmap==5.0.0',
    'text-unidecode==1.3',
    'urllib3==1.26.12',
]


[tool.briefcase.app.moviefinder.macOS]
requires = [
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.moviefinder.linux]
requires = []

[tool.briefcase.app.moviefinder.linux.appimage]
system_requires = []
linuxdeploy_plugins = []

[tool.briefcase.app.moviefinder.linux.flatpak]
flatpak_runtime = 'org.kde.Platform'
flatpak_runtime_version = '6.3'
flatpak_sdk = 'org.kde.Sdk'

[tool.briefcase.app.moviefinder.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.moviefinder.iOS]
supported = false

[tool.briefcase.app.moviefinder.android]
supported = false
